// DOM-only checks: no screen, browser automation, external request, or screenshots.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'../../docs/learn');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const tick=()=>new Promise(r=>setImmediate(r));
function boot(hash='#lesson-1',base='https://example.test/project/') {
 const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(read('index.html'),{url:base+hash,runScripts:'outside-only',virtualConsole:vc});
 const w=dom.window,d=w.document,requests=[];
 w.scrollTo=w.scrollBy=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.scrollTo=function(){};
 w.matchMedia=()=>({matches:false,addEventListener(){}});
 w.LEARNING_SITE={mode:'static',release:'release-test',assets:{'library.js':'library-hash','vendor/mermaid.min.js':'diagram-hash'}};
 const append=d.head.appendChild.bind(d.head);
 d.head.appendChild=node=>{if(node.tagName==='SCRIPT')requests.push(node);return append(node);};
 for(const n of ['assets.js','lessons.js','course.js','app.js','usability.js','reader.js'])w.eval(read(n));
 const trigger=(attrs)=>{const b=d.createElement('button');Object.assign(b.dataset,attrs);d.body.append(b);b.click();return b;};
 const finishLibrary=node=>{w.eval(read('library.js'));node.onload();};
 const finishDiagram=node=>{w.mermaid={initialize(){},async render(){return {svg:'<svg aria-label="diagram"></svg>'};}};node.onload();};
 return {dom,w,d,requests,errors,trigger,finishLibrary,finishDiagram};
}
(async()=>{
 const t=boot();const {w,d,requests}=t;
 assert.equal(requests.length,0,'first lesson must not load reference or diagrams');
 assert(!w.LEARNING_LIBRARY&&!w.mermaid);
 assert(d.getElementById('roadmap').textContent.includes('세부 강의 편성안'));
 await assert.rejects(w.LEARNING_ASSETS.load('constructor'));
 assert.equal(requests.length,0,'prototype names are not asset paths');
 t.trigger({source:'CMakeLists.txt'});t.trigger({doc:'part0'});
 assert.equal(requests.length,1,'concurrent reference requests share one script');
 assert.equal(new URL(requests[0].src).pathname,'/project/library.js');
 assert.equal(new URL(requests[0].src).searchParams.get('v'),'library-hash');
 assert.equal(w.LEARNING_ASSETS.load('library'),w.LEARNING_ASSETS.load('library'));
 d.getElementById('reader-close').click();t.finishLibrary(requests[0]);await tick();
 assert(d.getElementById('reference-reader').hidden,'loading must not reopen closed panel');
 t.trigger({source:'CMakeLists.txt'});await tick();
 assert.equal(requests.length,1);assert(d.getElementById('reader-body').textContent.includes('cmake_minimum_required'));
 assert(!d.getElementById('reader-body').textContent.includes('undefined'));
 t.dom.window.close();
 const retry=boot();retry.trigger({source:'CMakeLists.txt'});
 retry.requests[0].onerror();await tick();
 const button=retry.d.getElementById('reader-body').querySelector('button');assert(button);button.click();
 assert.equal(retry.requests.length,2);retry.finishLibrary(retry.requests[1]);await tick();
 assert(retry.d.getElementById('reader-body').textContent.includes('cmake_minimum_required'));
 retry.dom.window.close();
 const latest=boot();latest.trigger({source:'CMakeLists.txt'});latest.trigger({doc:'part0'});
 latest.finishLibrary(latest.requests[0]);await tick();
 assert.equal(latest.d.getElementById('reader-file').value,'part0','last requested document wins');
 assert.equal(latest.d.getElementById('reader-doc-mode').getAttribute('aria-pressed'),'true');
 latest.dom.window.close();
 const synchronous=boot();const append=synchronous.d.head.appendChild.bind(synchronous.d.head);
 synchronous.d.head.appendChild=()=>{throw Error('insertion blocked');};
 await assert.rejects(synchronous.w.LEARNING_ASSETS.load('library'));
 synchronous.d.head.appendChild=append;
 const retrying=synchronous.w.LEARNING_ASSETS.load('library');
 assert.equal(synchronous.requests.length,1,'synchronous insertion failure must allow retry');
 synchronous.finishLibrary(synchronous.requests[0]);await retrying;synchronous.dom.window.close();
 const diagram=boot('#lesson-138');await tick();
 assert.equal(diagram.requests.length,1);assert(diagram.requests[0].src.includes('mermaid.min.js'));
 assert(!diagram.w.LEARNING_LIBRARY,'lesson diagrams do not require reference bundle');
 diagram.finishDiagram(diagram.requests[0]);await tick();await tick();
 assert(diagram.d.querySelector('[data-diagram] svg'),'lesson diagram renders without opening reader');
 diagram.dom.window.close();
 // file:// and deployment subpaths both resolve relative to the entry file.
 const local=boot('#lesson-1','file:///tmp/learn/index.html');
 const loading=local.w.LEARNING_ASSETS.load('library');const node=local.requests[0];
 assert.equal(new URL(node.src).pathname,'/tmp/learn/library.js');node.onerror();await assert.rejects(loading);
 local.dom.window.close();
 console.log('Lazy assets: initial no-load, dedup, latest/closed request, retry, lesson diagrams, static versions, subpath and file URLs passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
