# Select the compiler target, then validate the chosen SDK layout.
# File presence does not prove binary ABI compatibility or deployment completeness.
function(tetris_import_onnxruntime root)
  if("${root}" STREQUAL "")
    message(FATAL_ERROR "tetris_import_onnxruntime: root argument is required")
  endif()

  get_filename_component(_tetris_root "${root}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(TARGET Tetris::OnnxRuntime)
    get_target_property(_tetris_existing Tetris::OnnxRuntime TETRIS_SDK_ROOT)
    if(NOT _tetris_existing STREQUAL _tetris_root)
      message(FATAL_ERROR "ONNX Runtime already imported from '${_tetris_existing}', cannot mix SDK roots")
    endif()
    return()
  endif()

  if(NOT CMAKE_SIZEOF_VOID_P)
    message(FATAL_ERROR "tetris_import_onnxruntime: CMAKE_SIZEOF_VOID_P is not defined; a 64-bit toolchain is required")
  endif()
  if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "tetris_import_onnxruntime: only 64-bit targets are supported (CMAKE_SIZEOF_VOID_P=${CMAKE_SIZEOF_VOID_P})")
  endif()

  string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _tetris_proc)

  set(_tetris_platform "")
  set(_tetris_runtime "")
  set(_tetris_implib "")

  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(_tetris_proc STREQUAL "x86_64" OR _tetris_proc STREQUAL "amd64")
      set(_tetris_platform "linux-x64")
    elseif(_tetris_proc STREQUAL "aarch64" OR _tetris_proc STREQUAL "arm64")
      set(_tetris_platform "linux-aarch64")
    else()
      message(FATAL_ERROR "tetris_import_onnxruntime: unsupported Linux processor '${CMAKE_SYSTEM_PROCESSOR}'")
    endif()
    set(_tetris_runtime "${_tetris_root}/lib/${_tetris_platform}/libonnxruntime.so")

  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_tetris_platform "osx-universal2")
    set(_tetris_arch_ok FALSE)
    if(_tetris_proc STREQUAL "x86_64" OR _tetris_proc STREQUAL "arm64" OR _tetris_proc STREQUAL "aarch64")
      set(_tetris_arch_ok TRUE)
    endif()
    if(CMAKE_OSX_ARCHITECTURES)
      set(_tetris_arch_ok FALSE)
      set(_tetris_osx_ok TRUE)
      foreach(_tetris_arch IN LISTS CMAKE_OSX_ARCHITECTURES)
        string(TOLOWER "${_tetris_arch}" _tetris_arch_lc)
        if(NOT _tetris_arch_lc STREQUAL "x86_64" AND NOT _tetris_arch_lc STREQUAL "arm64")
          set(_tetris_osx_ok FALSE)
        endif()
      endforeach()
      if(_tetris_osx_ok)
        set(_tetris_arch_ok TRUE)
      endif()
    endif()
    if(NOT _tetris_arch_ok)
      message(FATAL_ERROR "tetris_import_onnxruntime: unsupported Darwin processor '${CMAKE_SYSTEM_PROCESSOR}'")
    endif()
    set(_tetris_runtime "${_tetris_root}/lib/${_tetris_platform}/libonnxruntime.dylib")

  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    # Visual Studio resolves its target separately from the host processor.
    if(CMAKE_VS_PLATFORM_NAME)
      string(TOLOWER "${CMAKE_VS_PLATFORM_NAME}" _tetris_windows_target)
    elseif(CMAKE_GENERATOR_PLATFORM)
      string(REGEX REPLACE ",.*$" "" _tetris_windows_target "${CMAKE_GENERATOR_PLATFORM}")
      string(TOLOWER "${_tetris_windows_target}" _tetris_windows_target)
    else()
      set(_tetris_windows_target "${_tetris_proc}")
    endif()
    if(NOT _tetris_windows_target MATCHES "^(x64|x86_64|amd64)$")
      message(FATAL_ERROR "tetris_import_onnxruntime: unsupported Windows target '${_tetris_windows_target}'")
    endif()
    set(_tetris_platform "win-x64")
    set(_tetris_runtime "${_tetris_root}/lib/${_tetris_platform}/onnxruntime.dll")
    set(_tetris_implib "${_tetris_root}/lib/${_tetris_platform}/onnxruntime.lib")

  else()
    message(FATAL_ERROR "tetris_import_onnxruntime: unsupported system '${CMAKE_SYSTEM_NAME}'")
  endif()

  set(_tetris_include "${_tetris_root}/include")
  foreach(_tetris_header onnxruntime_cxx_api.h onnxruntime_c_api.h)
    if(NOT EXISTS "${_tetris_include}/${_tetris_header}" OR IS_DIRECTORY "${_tetris_include}/${_tetris_header}")
      message(FATAL_ERROR "tetris_import_onnxruntime: missing required header '${_tetris_include}/${_tetris_header}'")
    endif()
  endforeach()

  if(NOT EXISTS "${_tetris_runtime}" OR IS_DIRECTORY "${_tetris_runtime}")
    message(FATAL_ERROR "tetris_import_onnxruntime: missing runtime library '${_tetris_runtime}'")
  endif()
  if(_tetris_implib)
    if(NOT EXISTS "${_tetris_implib}" OR IS_DIRECTORY "${_tetris_implib}")
      message(FATAL_ERROR "tetris_import_onnxruntime: missing import library '${_tetris_implib}'")
    endif()
  endif()

  add_library(Tetris::OnnxRuntime SHARED IMPORTED GLOBAL)
  set_target_properties(Tetris::OnnxRuntime PROPERTIES
    TETRIS_SDK_ROOT "${_tetris_root}"
    IMPORTED_LOCATION "${_tetris_runtime}"
    INTERFACE_INCLUDE_DIRECTORIES "${_tetris_include}"
  )
  if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set_target_properties(Tetris::OnnxRuntime PROPERTIES
      IMPORTED_IMPLIB "${_tetris_implib}"
    )
  endif()
endfunction()
